import 'server-only';
import { PALETTE, FONT, FONT_FALLBACK, WORDMARK } from './theme';

/**
 * PDF — the same brand system, rendered through a headless browser.
 *
 * FEASIBILITY WAS ALREADY SETTLED. @sparticuz/chromium + puppeteer-core trace
 * to 70.1 MB against Vercel's 250 MB uncompressed limit (measured 2026-07-31),
 * and next.config.ts force-includes the brotli payload the tracer cannot see —
 * without which the function deploys clean and throws on the first request,
 * which is the worst failure shape available: a green build and a broken
 * button. What was missing was the template and the wiring.
 *
 * NO SUPABASE STORAGE. The PDF streams back exactly like the DOCX does. The
 * storage question belongs to the share route, where an artifact has to outlive
 * the request — folding it in here would have made a download depend on a
 * bucket that does not exist yet.
 */

/**
 * Where Chromium is.
 *
 * Two environments, and the split is explicit rather than a try/catch cascade.
 * On Vercel the Lambda-packaged build is the only one present; locally it is
 * whatever the machine has, and falling back to @sparticuz there produces a
 * confusing "libnss3 missing" rather than an honest "no browser configured".
 */
async function browserPaths(): Promise<{ executablePath: string; args: string[]; headless: boolean }> {
  const onLambda = Boolean(process.env.AWS_LAMBDA_FUNCTION_VERSION || process.env.VERCEL);

  if (onLambda) {
    const chromium = (await import('@sparticuz/chromium')).default;
    return {
      executablePath: await chromium.executablePath(),
      args: chromium.args,
      headless: true,
    };
  }

  const local = process.env.PDF_CHROMIUM_PATH;
  if (!local) {
    throw new Error(
      'No local Chromium configured. Set PDF_CHROMIUM_PATH to a Chrome or Chromium binary — ' +
        'the Lambda build from @sparticuz/chromium only runs on Lambda, and falling back to it ' +
        'here fails with a missing-library error that says nothing useful.',
    );
  }
  return {
    executablePath: local,
    args: ['--no-sandbox', '--disable-dev-shm-usage'],
    headless: true,
  };
}

export type PdfPageSize = 'Letter' | 'A4';

/**
 * Minimal, deliberate markdown → HTML.
 *
 * A full markdown library was rejected for the same reason the DOCX renderer
 * parses blocks itself: everything that reaches this function was generated by
 * a model, and a permissive renderer would happily emit raw HTML, an image tag
 * pointing anywhere, or a script — into a document that goes to a customer.
 * Only the constructs the generators actually produce are supported, and
 * everything else is escaped.
 */
function escapeHtml(s: string): string {
  return s
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

function inline(s: string): string {
  // Escape FIRST, then re-introduce only the two marks the generators emit.
  return escapeHtml(s)
    .replace(/\*\*([^*]+)\*\*/g, '<strong>$1</strong>')
    .replace(/(^|[^*])\*([^*]+)\*/g, '$1<em>$2</em>');
}

export function markdownToHtml(markdown: string): string {
  const out: string[] = [];
  let listOpen = false;

  const closeList = () => {
    if (listOpen) {
      out.push('</ul>');
      listOpen = false;
    }
  };

  for (const raw of markdown.split('\n')) {
    const line = raw.trimEnd();

    if (/^\s*$/.test(line)) {
      closeList();
      continue;
    }
    if (/^---+\s*$/.test(line)) {
      closeList();
      out.push('<hr />');
      continue;
    }
    const heading = line.match(/^(#{1,3})\s+(.*)$/);
    if (heading) {
      closeList();
      out.push(`<h${heading[1].length}>${inline(heading[2])}</h${heading[1].length}>`);
      continue;
    }
    const bullet = line.match(/^\s*[-*•]\s+(.*)$/);
    if (bullet) {
      if (!listOpen) {
        out.push('<ul>');
        listOpen = true;
      }
      out.push(`<li>${inline(bullet[1])}</li>`);
      continue;
    }
    closeList();
    out.push(`<p>${inline(line)}</p>`);
  }
  closeList();
  return out.join('\n');
}

/**
 * The page shell.
 *
 * Reads PALETTE rather than restating hexes, so this is not a fourth place the
 * brand can drift. The header band matches the DOCX at 0.65in with the
 * PowerDeal wordmark and no partner mark — the same permission decision, in the
 * same fixed box.
 */
export function pdfHtml(opts: {
  title: string;
  subtitle: string;
  body: string;
}): string {
  return `<!doctype html>
<html><head><meta charset="utf-8" />
<style>
  @page { margin: 0.75in; }
  * { box-sizing: border-box; }
  body {
    font-family: '${FONT}', '${FONT_FALLBACK}', system-ui, sans-serif;
    color: #${PALETTE.charcoal};
    font-size: 10.5pt;
    line-height: 1.45;
    margin: 0;
  }
  .band {
    height: 0.65in;
    background: #${PALETTE.headerFill};
    border-bottom: 1px solid #${PALETTE.rule};
    display: flex; align-items: center; padding: 0 0.2in;
    font-size: 9pt; letter-spacing: 0.08em; text-transform: uppercase;
    color: #${PALETTE.muted};
  }
  h1 { font-size: 20pt; margin: 0.25in 0 0.04in; }
  h2 { font-size: 13pt; margin: 0.22in 0 0.04in; }
  h3 { font-size: 11pt; margin: 0.18in 0 0.04in; }
  h1, h2, h3 { color: #${PALETTE.charcoal}; page-break-after: avoid; }
  .sub { color: #${PALETTE.muted}; font-size: 9.5pt; margin: 0 0 0.1in; }
  /* Accent only: a rule, never a fill behind type, never a heading colour. */
  .rule { height: 3px; width: 0.5in; background: #${PALETTE.bloom}; margin: 0.06in 0 0.2in; }
  hr { border: 0; border-top: 1px solid #${PALETTE.ruleFaint}; margin: 0.18in 0; }
  ul { margin: 0.06in 0 0.06in 0.22in; padding: 0; }
  li { margin: 0.03in 0; }
  p { margin: 0.06in 0; }
  strong { font-weight: 600; }
</style></head>
<body>
  <div class="band">${escapeHtml(WORDMARK)}</div>
  <h1>${escapeHtml(opts.title)}</h1>
  <p class="sub">${escapeHtml(opts.subtitle)}</p>
  <div class="rule"></div>
  ${opts.body}
</body></html>`;
}

export async function generatePdf(
  title: string,
  subtitle: string,
  markdown: string,
  pageSize: PdfPageSize = 'Letter',
): Promise<Buffer> {
  const { executablePath, args, headless } = await browserPaths();
  const puppeteer = (await import('puppeteer-core')).default;

  const browser = await puppeteer.launch({ executablePath, args, headless });
  try {
    const page = await browser.newPage();
    await page.setContent(pdfHtml({ title, subtitle, body: markdownToHtml(markdown) }), {
      // 'load' rather than 'networkidle0': the document embeds nothing and
      // fetches nothing, so waiting on the network would only ever wait.
      waitUntil: 'load',
    });
    const pdf = await page.pdf({
      format: pageSize,
      printBackground: true,
      // Margins live in @page so the header band can bleed to the edge.
      margin: { top: '0', right: '0', bottom: '0', left: '0' },
    });
    return Buffer.from(pdf);
  } finally {
    // Always. A leaked browser on a serverless invocation holds the function
    // open until the platform kills it, and bills for the wait.
    await browser.close();
  }
}
